/*USE AULA_BD;*/
CREATE TABLE AULA_BD.DEPARTAMENTO 
	(ID INT(19) AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50));
    
CREATE TABLE `aula_bd`.`departamento2` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `aula_bd`.`departamento3` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
  
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAELN');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAELT');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAINF');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAMEC');

INSERT INTO AULA_BD.DEPARTAMENTO3 (ID,NOME) VALUES (5,'DAELN');
INSERT INTO AULA_BD.DEPARTAMENTO3 (ID,NOME) VALUES (6,'DAELT');

DELETE FROM AULA_BD.departamento3;

UPDATE AULA_BD.DEPARTAMENTO SET NOME = 'DAELN2' WHERE ID = 2;

DROP TABLE AULA_BD.DEPARTAMENTO2;
DROP TABLE AULA_BD.DEPARTAMENTO3;


/*CRIAR TABELA ALUNO COM ID, NOME E DT_NASCIMENTO*/
CREATE TABLE AULA_BD.ALUNO (ID INT NOT NULL AUTO_INCREMENT,NOME VARCHAR(45) NOT NULL, DT_NASCIMENTO DATE NOT NULL,PRIMARY KEY (ID));

ALTER TABLE AULA_BD.ALUNO ADD COLUMN TELEFONE VARCHAR(10) NULL;
/*ALTER TABLE AULA_BD.ALUNO DROP COLUMN TELEFONE2;*/

INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Leonardo',DATE('1990-11-05'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Karina',DATE('1993-05-17'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('João',DATE('1989-06-10'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('João',DATE('1981-07-15'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('José',DATE('1985-03-11'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Mario',DATE('1989-03-11'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Maria',DATE('1982-03-11'));

UPDATE AULA_BD.ALUNO SET TELEFONE = '3333-3333' WHERE NOME = 'Leonardo';

select * from AULA_BD.ALUNO;

ALTER TABLE AULA_BD.ALUNO ADD COLUMN ID_DEPARTAMENTO INT NULL;

ALTER TABLE AULA_BD.ALUNO 
ADD CONSTRAINT FK_ALUNO_DEPARTAMETO
  FOREIGN KEY (ID_DEPARTAMENTO)
  REFERENCES AULA_BD.departamento (ID);
  
SELECT NOME,ID_DEPARTAMENTO FROM AULA_BD.ALUNO;

UPDATE AULA_BD.ALUNO SET ID_DEPARTAMENTO = 1 WHERE NOME = 'Leonardo';
UPDATE AULA_BD.ALUNO SET ID_DEPARTAMENTO = 2 WHERE NOME = 'Karina';
UPDATE AULA_BD.ALUNO SET ID_DEPARTAMENTO = 3 WHERE NOME = 'João';

SELECT NOME,ID_DEPARTAMENTO FROM AULA_BD.ALUNO
WHERE ID_DEPARTAMENTO = 1 OR ID_DEPARTAMENTO = 2;

SELECT 
    NOME, ID_DEPARTAMENTO, DT_NASCIMENTO
FROM
    AULA_BD.ALUNO
WHERE
    ID_DEPARTAMENTO = 3
AND DT_NASCIMENTO > DATE('1982-01-01');

SELECT DISTINCT NOME, ID_DEPARTAMENTO FROM AULA_BD.ALUNO;

SELECT * FROM AULA_BD.ALUNO;
SELECT * FROM AULA_BD.DEPARTAMENTO;

SELECT * FROM AULA_BD.ALUNO, AULA_BD.DEPARTAMENTO
WHERE AULA_BD.ALUNO.ID_DEPARTAMENTO = AULA_BD.DEPARTAMENTO.ID;

SELECT AULA_BD.ALUNO.NOME, AULA_BD.DEPARTAMENTO.NOME FROM AULA_BD.ALUNO, AULA_BD.DEPARTAMENTO
WHERE AULA_BD.ALUNO.ID_DEPARTAMENTO = AULA_BD.DEPARTAMENTO.ID;

SELECT * FROM AULA_BD.ALUNO
JOIN AULA_BD.DEPARTAMENTO;

SELECT * FROM AULA_BD.ALUNO
JOIN AULA_BD.DEPARTAMENTO 
ON AULA_BD.ALUNO.ID_DEPARTAMENTO = AULA_BD.DEPARTAMENTO.ID
WHERE DT_NASCIMENTO < DATE('1992-01-01');

SELECT * FROM AULA_BD.ALUNO
LEFT JOIN AULA_BD.DEPARTAMENTO 
ON AULA_BD.ALUNO.ID_DEPARTAMENTO = AULA_BD.DEPARTAMENTO.ID;

SELECT * FROM AULA_BD.ALUNO
RIGHT JOIN AULA_BD.DEPARTAMENTO 
ON AULA_BD.ALUNO.ID_DEPARTAMENTO = AULA_BD.DEPARTAMENTO.ID;

SELECT * FROM AULA_BD.DEPARTAMENTO
LEFT JOIN AULA_BD.ALUNO 
ON AULA_BD.ALUNO.ID_DEPARTAMENTO = AULA_BD.DEPARTAMENTO.ID;

SELECT  AL.NOME AS NOME_ALUNO, 
		DP.NOME AS NOME_DEPT 
FROM AULA_BD.ALUNO AL
JOIN AULA_BD.DEPARTAMENTO DP ON AL.ID_DEPARTAMENTO = DP.ID;

SELECT * FROM AULA_BD.ALUNO WHERE NOME = 'Leonardo';
SELECT * FROM AULA_BD.DEPARTAMENTO WHERE NOME LIKE '%n%';
SELECT * FROM AULA_BD.ALUNO WHERE NOME LIKE 'Mari_';

CREATE TABLE AULA_BD.NOTA 
  (ID INT(19) AUTO_INCREMENT PRIMARY KEY,
   ID_ALUNO INT(19),
   VALOR_NOTA NUMERIC (4,2),
   ANO INT(19),
   SEMESTRE INT(19),
   CONSTRAINT FK_NOTA_ALUNO 
   FOREIGN KEY (ID_ALUNO) REFERENCES AULA_BD.ALUNO (ID));
   
INSERT INTO AULA_BD.NOTA (ID_ALUNO,VALOR_NOTA,ANO,SEMESTRE) VALUES
((SELECT ID FROM AULA_BD.ALUNO WHERE NOME = 'Leonardo'),8.90,2017,2);
INSERT INTO AULA_BD.NOTA (ID_ALUNO,VALOR_NOTA,ANO,SEMESTRE) VALUES
((SELECT ID FROM AULA_BD.ALUNO WHERE NOME = 'Leonardo'),9.90,2017,2);
INSERT INTO AULA_BD.NOTA (ID_ALUNO,VALOR_NOTA,ANO,SEMESTRE) VALUES
((SELECT ID FROM AULA_BD.ALUNO WHERE NOME = 'Karina'),9.00,2017,2);
INSERT INTO AULA_BD.NOTA (ID_ALUNO,VALOR_NOTA,ANO,SEMESTRE) VALUES
((SELECT ID FROM AULA_BD.ALUNO WHERE NOME = 'Karina'),7.00,2017,2);
INSERT INTO AULA_BD.NOTA (ID_ALUNO,VALOR_NOTA,ANO,SEMESTRE) VALUES
((SELECT ID FROM AULA_BD.ALUNO WHERE NOME = 'José'),6.00,2017,2);

SELECT  AL.NOME AS NOME_ALUNO, 
		NT.VALOR_NOTA AS NOTA 
FROM AULA_BD.NOTA NT
JOIN AULA_BD.ALUNO AL ON AL.ID = NT.ID_ALUNO
ORDER BY VALOR_NOTA DESC;

SELECT  AL.NOME AS NOME_ALUNO, 
		NT.VALOR_NOTA AS NOTA 
FROM AULA_BD.NOTA NT
JOIN AULA_BD.ALUNO AL ON AL.ID = NT.ID_ALUNO
WHERE NT.VALOR_NOTA not between 8.5 and 9.5
ORDER BY VALOR_NOTA DESC;

SELECT NOME FROM AULA_BD.ALUNO
UNION 
SELECT NOME FROM AULA_BD.DEPARTAMENTO;

SELECT NOME FROM AULA_BD.ALUNO
UNION ALL
SELECT NOME FROM AULA_BD.DEPARTAMENTO;

SELECT NOME, DT_NASCIMENTO FROM AULA_BD.ALUNO
UNION ALL
SELECT NOME, NULL FROM AULA_BD.DEPARTAMENTO;

SELECT NOME, DT_NASCIMENTO, TELEFONE FROM AULA_BD.ALUNO
WHERE TELEFONE IS NULL;

SELECT NOME, DT_NASCIMENTO, TELEFONE FROM AULA_BD.ALUNO
WHERE TELEFONE IS NOT NULL;

select AVG(VALOR_NOTA) from AULA_BD.NOTA;
select MAX(VALOR_NOTA) from AULA_BD.NOTA;
select COUNT(id_aluno) from AULA_BD.NOTA;

select AL.NOME, MAX(NT.VALOR_NOTA) FROM AULA_BD.NOTA NT
JOIN AULA_BD.ALUNO AL ON AL.ID = NT.ID_ALUNO
GROUP BY AL.NOME;

select AL.NOME, AVG(NT.VALOR_NOTA) FROM AULA_BD.NOTA NT
JOIN AULA_BD.ALUNO AL ON AL.ID = NT.ID_ALUNO
GROUP BY AL.NOME;

select AL.NOME, AVG(NT.VALOR_NOTA) FROM AULA_BD.NOTA NT
JOIN AULA_BD.ALUNO AL ON AL.ID = NT.ID_ALUNO
GROUP BY AL.NOME
HAVING AVG(NT.VALOR_NOTA) > 7;

select AL.NOME,COUNT(AL.NOME) from AULA_BD.NOTA NT
JOIN AULA_BD.ALUNO AL ON AL.ID = NT.ID_ALUNO
GROUP BY AL.NOME;

select AL.NOME, 
	(SELECT COUNT(*) FROM AULA_BD.ALUNO AL_AUX where AL.NOME = AL_AUX.NOME) as NUM_NOME_REPT
FROM AULA_BD.ALUNO AL;