CREATE TABLE AULA_BD.DEPARTAMENTO 
	(ID INT(19) AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50));

CREATE TABLE AULA_BD.ALUNO (ID INT NOT NULL AUTO_INCREMENT,NOME VARCHAR(45) NOT NULL, DT_NASCIMENTO DATE NOT NULL,PRIMARY KEY (ID));

ALTER TABLE AULA_BD.ALUNO ADD COLUMN TELEFONE VARCHAR(10) NULL;

ALTER TABLE AULA_BD.ALUNO ADD COLUMN ID_DEPARTAMENTO INT NULL;

ALTER TABLE AULA_BD.ALUNO 
ADD CONSTRAINT FK_ALUNO_DEPARTAMETO
  FOREIGN KEY (ID_DEPARTAMENTO)
  REFERENCES AULA_BD.DEPARTAMENTO (ID);


INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAELN');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAELT');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAINF');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAMEC');

INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Leonardo',DATE('1990-11-05'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Karina',DATE('1993-05-17'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('João',DATE('1989-06-10'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('João',DATE('1981-07-15'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('José',DATE('1985-03-11'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Mario',DATE('1989-03-11'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Maria',DATE('1982-03-11'));

INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO, TELEFONE) VALUES ('Maria',DATE('1982-03-11'), '3333-3333');

SELECT * FROM ALUNO AL;

SELECT ALUNO.NOME, DT_NASCIMENTO, DEPARTAMENTO.NOME FROM ALUNO, DEPARTAMENTO
WHERE ALUNO.ID_DEPARTAMENTO = DEPARTAMENTO.ID;

SELECT AL.TELEFONE, AL.NOME AS NOME_ALUNO , DP.NOME AS NOME_DPTO
	FROM AULA_BD.ALUNO AL
	JOIN AULA_BD.DEPARTAMENTO DP ON DP.ID = AL.ID_DEPARTAMENTO;
    
SELECT AL.NOME AS NOME_ALUNO , DP.NOME AS NOME_DPTO
	FROM AULA_BD.ALUNO AL
	RIGHT JOIN AULA_BD.DEPARTAMENTO DP ON DP.ID = AL.ID_DEPARTAMENTO;