/*USE AULA_BD;*/
CREATE TABLE AULA_BD.DEPARTAMENTO 
	(ID INT(19) AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50));
    
CREATE TABLE `aula_bd`.`departamento2` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
  
CREATE TABLE `aula_bd`.`departamento3` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
  
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAELN');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAELT');
INSERT INTO AULA_BD.DEPARTAMENTO (NOME) VALUES ('DAINF');

INSERT INTO AULA_BD.DEPARTAMENTO3 (ID,NOME) VALUES (5,'DAELN');
INSERT INTO AULA_BD.DEPARTAMENTO3 (ID,NOME) VALUES (6,'DAELT');

DELETE FROM AULA_BD.departamento3;

UPDATE AULA_BD.DEPARTAMENTO SET NOME = 'DAELN2' WHERE ID = 2;

DROP TABLE AULA_BD.DEPARTAMENTO2;
DROP TABLE AULA_BD.DEPARTAMENTO3;


/*CRIAR TABELA ALUNO COM ID, NOME E DT_NASCIMENTO*/
CREATE TABLE AULA_BD.ALUNO (ID INT NOT NULL AUTO_INCREMENT,NOME VARCHAR(45) NOT NULL, DT_NASCIMENTO DATE NOT NULL,PRIMARY KEY (ID));

ALTER TABLE AULA_BD.ALUNO ADD COLUMN TELEFONE VARCHAR(10) NULL;
/*ALTER TABLE AULA_BD.ALUNO DROP COLUMN TELEFONE2;*/

INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Leonardo',DATE('1990-11-05'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('Karina',DATE('1993-05-17'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('João',DATE('1989-06-10'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('João',DATE('1981-07-15'));
INSERT INTO AULA_BD.ALUNO(NOME,DT_NASCIMENTO) VALUES ('José',DATE('1985-03-11'));

UPDATE AULA_BD.ALUNO SET TELEFONE = '3333-3333' WHERE NOME = 'Leonardo';

select * from AULA_BD.ALUNO;

ALTER TABLE AULA_BD.ALUNO ADD COLUMN ID_DEPARTAMENTO INT NULL;

ALTER TABLE AULA_BD.ALUNO 
ADD CONSTRAINT FK_ALUNO_DEPARTAMETO
  FOREIGN KEY (ID_DEPARTAMENTO)
  REFERENCES AULA_BD.departamento (ID);
  
SELECT NOME,ID_DEPARTAMENTO FROM AULA_BD.ALUNO;

UPDATE AULA_BD.ALUNO SET ID_DEPARTAMENTO = 1 WHERE NOME = 'Leonardo';
UPDATE AULA_BD.ALUNO SET ID_DEPARTAMENTO = 2 WHERE NOME = 'Karina';
UPDATE AULA_BD.ALUNO SET ID_DEPARTAMENTO = 3 WHERE NOME = 'João';

SELECT NOME,ID_DEPARTAMENTO FROM AULA_BD.ALUNO
WHERE ID_DEPARTAMENTO = 1 OR ID_DEPARTAMENTO = 2;

SELECT 
    NOME, ID_DEPARTAMENTO, DT_NASCIMENTO
FROM
    AULA_BD.ALUNO
WHERE
    ID_DEPARTAMENTO = 3;
/*AND DT_NASCIMENTO > DATE('1982-01-01');